"""Write programmes.js: the catalogue data (PROGS) the website's Training section renders.

    python scripts/programme_site.py

Run after build_programmes.py, like programme_index.py. Course order and slugs come from the title table in
W:/trainings-catalog/HANDOFF.md; text comes from programmes/<slug>.json (English) and <slug>-fr.json (French).
"""
import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'programmes'
HANDOFF = Path('W:/trainings-catalog/HANDOFF.md')
# Website tabs (keys match data-group in index.html #training): last course number of each tab
GROUPS = [('infra', 11), ('cloud', 23), ('data', 34), ('sec', 38), ('acad', 39)]


def fact(g, label):
    return next(f['value'] for f in g['facts'] if f['label'] == label)


def both(en, fr):
    return {'en': en, 'fr': fr}


def main():
    rows = re.findall(r'^\| (\d+) \| (.+?) \| (.+?) \| `(.+?)` \|$', HANDOFF.read_text(encoding='utf-8'), re.M)
    progs = {k: [] for k, _ in GROUPS}
    for n, _, _, slug in rows:
        en = json.loads((SRC / f'{slug}.json').read_text(encoding='utf-8'))
        fr = json.loads((SRC / f'{slug}-fr.json').read_text(encoding='utf-8'))
        core = [p for p in en['phases'] if not p.get('optional')]
        opt = sum(p['hours'] for p in en['phases'] if p.get('optional'))
        progs[next(k for k, last in GROUPS if int(n) <= last)].append({
            'n': int(n),
            'h': sum(p['hours'] for p in core) + (en.get('buffer') or 0),
            'opt': opt or None,
            'title': both(en['title'], fr['title']),
            'sub': both(en['subtitle'], fr['subtitle']),
            'aud': both(fact(en, 'Audience'), fact(fr, 'Public')),
            'pre': both(fact(en, 'Prerequisites'), fact(fr, 'Prérequis')),
            'cert': both(en['certifications'], fr['certifications']) if en['certifications'] else None,
            'ph': [[both(a['name'], b['name']), both(a['focus'], b['focus']), a['hours'], bool(a.get('optional'))]
                   for a, b in zip(en['phases'], fr['phases'])],
            'buf': en.get('buffer') or None,
            'file': both(Path(en['file']).stem, Path(fr['file']).stem),
        })
    js = ('/* Generated by scripts/programme_site.py from programmes/*.json: do not edit by hand. */\n'
          '/* Training catalogue, one key per tab. file = stem of res/programmes/<file>.docx and res/programmes/pdf/<file>.pdf */\n'
          'const PROGS = {\n' + ',\n'.join(
              f'{k}: [\n' + ',\n'.join(json.dumps(c, ensure_ascii=False, separators=(',', ':')) for c in v) + ']'
              for k, v in progs.items()) + '\n};\n')
    (ROOT / 'programmes.js').write_text(js, encoding='utf-8')
    print(f'wrote programmes.js ({sum(map(len, progs.values()))} courses)')


if __name__ == '__main__':
    main()
